spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: pranavparalkar21@gmail.com
    password: htlg szif sqyv ndbc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:455604515008-pt1ijtiflfhb2hh1e8ouaf43vpq69vj3.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - email
              - profile

app:
  oauth2:
    authorizedRedirectUris: ${FRONTEND_OAUTH2_REDIRECT_URL:http://localhost:5173/oauth-success}

razorpay:
  key-id: rzp_test_SdRTnYdewXJLXX
  key-secret: JBSXB6A2ZUI3aMXEultFo89f

subscription:
  free-document-limit: 3
  premium-document-limit: 50
  free-upload-limit: 3
  monthly-price-paise: 2900
  plan-name: Prescribe Pro

aws:
  s3:
    bucket: prescribe-bucket-new
    region: ap-south-1
  credentials:
    access-key: AKIA5E7OD3LZZAMEFKCF
    secret-key: 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
spring.servlet.multipart:
  max-file-size: 50MB
  max-request-size: 55MB

server:
  port: 8080